version: '3.8'

services:
  php-app:
    build:
      context: .
    ports:
      - "8080:80" # Le port 8080 de votre machine redirige vers le port 80 du conteneur
    volumes:
      - .:/var/www/html # Synchronisation entre votre dossier local et le conteneur
